kind: pipeline
name: simple_testing

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  golang-simple-test:
    image: golang:1.11
    pull: true
    commands:
      - go test ./drone/testpkg/ -v
      - go test ./drone/testpkg/ -bench=. -v
      - go test ./consistency/ -v
      - go test ./ann-service/pianogame/utils/ -v
      - go test -timeout 30s ./grpc_helloworld/mock_helloworld