web_service:
  addrs:
    - hostname: ""
      port: 80
    - hostname: ""
      port: 443
    - hostname: ""
      port: 8081

  static:
    images: "pianogame/static/images"
    css: "pianogame/static/css"
    js: "pianogame/static/js"
    music: "pianogame/static/music"

  html_templates: [
    "pianogame/templates/Signup.html",
    "pianogame/templates/Login.html",
    "pianogame/templates/Gamepage.html",
    "pianogame/templates/AnnPage.html"
  ]