// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pianoplay.proto

package pianoplay

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// message interfaces here
type UserData struct {
	UUID                 string   `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	PianoKey             string   `protobuf:"bytes,2,opt,name=PianoKey,proto3" json:"PianoKey,omitempty"`
	To                   string   `protobuf:"bytes,3,opt,name=To,proto3" json:"To,omitempty"`
	From                 string   `protobuf:"bytes,4,opt,name=From,proto3" json:"From,omitempty"`
	Text                 string   `protobuf:"bytes,5,opt,name=Text,proto3" json:"Text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}
func (*UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_pianoplay_e6dc9a3d67b11fa8, []int{0}
}
func (m *UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserData.Unmarshal(m, b)
}
func (m *UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserData.Marshal(b, m, deterministic)
}
func (dst *UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserData.Merge(dst, src)
}
func (m *UserData) XXX_Size() int {
	return xxx_messageInfo_UserData.Size(m)
}
func (m *UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_UserData proto.InternalMessageInfo

func (m *UserData) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *UserData) GetPianoKey() string {
	if m != nil {
		return m.PianoKey
	}
	return ""
}

func (m *UserData) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *UserData) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *UserData) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_pianoplay_e6dc9a3d67b11fa8, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*UserData)(nil), "pianoplay.UserData")
	proto.RegisterType((*Response)(nil), "pianoplay.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PianoplayGreeterClient is the client API for PianoplayGreeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PianoplayGreeterClient interface {
	Save(ctx context.Context, in *UserData, opts ...grpc.CallOption) (*Response, error)
}

type pianoplayGreeterClient struct {
	cc *grpc.ClientConn
}

func NewPianoplayGreeterClient(cc *grpc.ClientConn) PianoplayGreeterClient {
	return &pianoplayGreeterClient{cc}
}

func (c *pianoplayGreeterClient) Save(ctx context.Context, in *UserData, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pianoplay.PianoplayGreeter/Save", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PianoplayGreeterServer is the server API for PianoplayGreeter service.
type PianoplayGreeterServer interface {
	Save(context.Context, *UserData) (*Response, error)
}

func RegisterPianoplayGreeterServer(s *grpc.Server, srv PianoplayGreeterServer) {
	s.RegisterService(&_PianoplayGreeter_serviceDesc, srv)
}

func _PianoplayGreeter_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PianoplayGreeterServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pianoplay.PianoplayGreeter/Save",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PianoplayGreeterServer).Save(ctx, req.(*UserData))
	}
	return interceptor(ctx, in, info, handler)
}

var _PianoplayGreeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pianoplay.PianoplayGreeter",
	HandlerType: (*PianoplayGreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Save",
			Handler:    _PianoplayGreeter_Save_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pianoplay.proto",
}

func init() { proto.RegisterFile("pianoplay.proto", fileDescriptor_pianoplay_e6dc9a3d67b11fa8) }

var fileDescriptor_pianoplay_e6dc9a3d67b11fa8 = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x90, 0xcb, 0x4a, 0xc5, 0x30,
	0x10, 0x86, 0xed, 0x45, 0x4d, 0x67, 0xa1, 0x65, 0xdc, 0x84, 0xae, 0xa4, 0x2b, 0x57, 0x5d, 0x54,
	0xf0, 0x09, 0x4a, 0x45, 0x44, 0x28, 0xbd, 0x3c, 0x40, 0x2c, 0x83, 0x08, 0xda, 0x84, 0x24, 0x8a,
	0x7d, 0x7b, 0x4f, 0xd2, 0x93, 0x9e, 0xb3, 0xfb, 0xe6, 0x23, 0xc3, 0x9f, 0x7f, 0xe0, 0x56, 0x7d,
	0x8a, 0x45, 0xaa, 0x2f, 0xb1, 0x56, 0x4a, 0x4b, 0x2b, 0x31, 0xdb, 0x45, 0xa9, 0x81, 0x4d, 0x86,
	0x74, 0x23, 0xac, 0x40, 0x84, 0x74, 0x9a, 0x5e, 0x1a, 0x1e, 0xdd, 0x47, 0x0f, 0x59, 0xef, 0x19,
	0x0b, 0x60, 0x9d, 0x7b, 0xfc, 0x4a, 0x2b, 0x8f, 0xbd, 0xdf, 0x67, 0xbc, 0x81, 0x78, 0x94, 0x3c,
	0xf1, 0xf6, 0x40, 0x6e, 0xbf, 0xd5, 0xf2, 0x9b, 0xa7, 0xdb, 0xbe, 0x63, 0xe7, 0x46, 0xfa, 0xb3,
	0xfc, 0x72, 0x73, 0x8e, 0xcb, 0x27, 0x60, 0x3d, 0x19, 0x25, 0x17, 0x43, 0xc8, 0xe1, 0x7a, 0xf8,
	0x99, 0x67, 0x32, 0xc6, 0xc7, 0xb2, 0x3e, 0x8c, 0x98, 0x43, 0xf2, 0x66, 0x3e, 0x8e, 0xa1, 0x0e,
	0xeb, 0x16, 0xf2, 0x2e, 0x7c, 0xfc, 0x59, 0x13, 0x59, 0xd2, 0x58, 0x43, 0x3a, 0x88, 0x5f, 0xc2,
	0xbb, 0xea, 0x54, 0x32, 0x14, 0x2a, 0xce, 0x65, 0x48, 0x2c, 0x2f, 0xde, 0xaf, 0xfc, 0x15, 0x1e,
	0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0xa7, 0xf2, 0xb8, 0x40, 0x18, 0x01, 0x00, 0x00,
}
