httpserver:
  addr: "localhost:3000"
  mode: "test"
  # TODO tls

third-party-api:
  nasa:
    api_key: "key-from-Nasa"

databases:
  main:
    type: "postgresql" # or "mysql"
    dsn: "host=localhost user=user password=pwd" # ref the dsn
    max_open_conns: 100
    max_idle_conns: 10
    conn_max_life_time_second: 60 # 60 seconds
  redis:
    password: "redis-pwd"
    addr: "localhost:6379"

    
  
