debug: true
html_templates: [
  "pianogame/templates/Signup.html",
  "pianogame/templates/Login.html",
  "pianogame/templates/Gamepage.html",
  "pianogame/templates/AnnPage.html"
]
static:
  images: "pianogame/static/images"
  css: "pianogame/static/css"
  js: "pianogame/static/js"
  music: "pianogame/static/music"
jwtSecret: "secret"
ssl:
  cert: "ssl/localhost.pem"
  key: "ssl/localhost.key"
ports: [8443, 1234, 9999]
ip: ""

# new config structure mockup
web_service: # move to web.yaml
  ip: ""
  ports: [80, 443]
  ssl:
    cert: "ssl/localhost-mac.pem"
    key: "ssl/localhost-mac.key"
  static:
    images: "pianogame/static/images"
    css: "pianogame/static/css"
    js: "pianogame/static/js"
    music: "pianogame/static/music"
  html_templates: [
    "pianogame/templates/Signup.html",
    "pianogame/templates/Login.html",
    "pianogame/templates/Gamepage.html",
    "pianogame/templates/AnnPage.html"
  ]
  jwtSecret: "secret"

api_service: # stay here
  ip: ""
  ports: [8080, 8443]
  ssl:
    cert: "ssl/localhost-mac.pem"
    key: "ssl/localhost-mac.key"
  jwtSecret: "secret"

develop: # move to system.yaml
  debug: true